"""login failures

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 20:20:48.437557

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_failures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_failures_attempted_at"), "login_failures", ["attempted_at"], unique=False
    )
    op.create_index(op.f("ix_login_failures_email"), "login_failures", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_failures_email"), table_name="login_failures")
    op.drop_index(op.f("ix_login_failures_attempted_at"), table_name="login_failures")
    op.drop_table("login_failures")
    # ### end Alembic commands ###
