"""accounts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 08:17:12.022027

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "savings",
                "current",
                "credit_card",
                "wallet",
                "cash",
                "fd",
                "rd",
                "loan",
                "pot",
                name="accounttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=100), nullable=True),
        sa.Column(
            "capture_mode",
            sa.Enum(
                "statement_import",
                "manual_only",
                "hybrid",
                name="capturemode",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("opening_balance_paise", sa.BigInteger(), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("statement_day", sa.Integer(), nullable=True),
        sa.Column("due_day", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capture_mode IN ('statement_import', 'manual_only', 'hybrid')",
            name="ck_accounts_capture_mode",
        ),
        sa.CheckConstraint(
            "type = 'pot' AND parent_id IS NOT NULL OR type <> 'pot' AND parent_id IS NULL",
            name="ck_accounts_pot_needs_parent",
        ),
        sa.CheckConstraint(
            "type IN ('savings', 'current', 'credit_card', 'wallet', 'cash', 'fd', 'rd', 'loan', 'pot')",
            name="ck_accounts_type",
        ),
        sa.CheckConstraint(
            "due_day IS NULL OR due_day BETWEEN 1 AND 31", name="ck_accounts_due_day_range"
        ),
        sa.CheckConstraint(
            "statement_day IS NULL OR statement_day BETWEEN 1 AND 31",
            name="ck_accounts_statement_day_range",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
