"""interest rates

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 08:45:05.954894

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interest_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "daily",
                "monthly",
                "quarterly",
                "yearly",
                name="ratefrequency",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('daily', 'monthly', 'quarterly', 'yearly')",
            name="ck_interest_rates_frequency",
        ),
        sa.CheckConstraint("rate >= 0", name="ck_interest_rates_rate_non_negative"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interest_rates_account_id"), "interest_rates", ["account_id"], unique=False
    )
    # Partial, so soft-deleted rows do not block the same date being re-added.
    op.create_index(
        "uq_interest_rates_account_from_date",
        "interest_rates",
        ["account_id", "from_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_interest_rates_account_from_date",
        table_name="interest_rates",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_interest_rates_account_id"), table_name="interest_rates")
    op.drop_table("interest_rates")
    # ### end Alembic commands ###
