"""balance checks

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 17:13:35.283048

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("checked_on", sa.Date(), nullable=False),
        sa.Column("computed_paise", sa.BigInteger(), nullable=False),
        sa.Column("stated_paise", sa.BigInteger(), nullable=False),
        sa.Column("difference_paise", sa.BigInteger(), nullable=False),
        sa.Column("adjustment_posting_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_posting_id"],
            ["postings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_checks_account_id"), "balance_checks", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_balance_checks_adjustment_posting_id"),
        "balance_checks",
        ["adjustment_posting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_balance_checks_checked_on"), "balance_checks", ["checked_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_balance_checks_checked_on"), table_name="balance_checks")
    op.drop_index(op.f("ix_balance_checks_adjustment_posting_id"), table_name="balance_checks")
    op.drop_index(op.f("ix_balance_checks_account_id"), table_name="balance_checks")
    op.drop_table("balance_checks")
    # ### end Alembic commands ###
