/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Health
     * @description Report service and database status; the check really queries Postgres.
     */
    get: operations['read_health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Verify credentials, start a session and set the session cookie.
     */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description End the session and clear the cookie.
     */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Me
     * @description Return the signed-in user.
     */
    get: operations['read_me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description List the signed-in user's live accounts, oldest first.
     */
    get: operations['index_api_v1_accounts_get']
    put?: never
    /**
     * Create
     * @description Create an account for the signed-in user.
     */
    post: operations['create_api_v1_accounts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Show
     * @description Return one account, or 404 when it is unknown or soft-deleted.
     */
    get: operations['show_api_v1_accounts__account_id__get']
    put?: never
    post?: never
    /**
     * Destroy
     * @description Soft-delete an account. The row and its history are kept.
     */
    delete: operations['destroy_api_v1_accounts__account_id__delete']
    options?: never
    head?: never
    /**
     * Patch
     * @description Apply the provided fields to an account. `type` cannot change.
     */
    patch: operations['patch_api_v1_accounts__account_id__patch']
    trace?: never
  }
  '/api/v1/accounts/{account_id}/balance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Balance
     * @description The account's balance, and the two figures it was worked out from.
     */
    get: operations['read_balance_api_v1_accounts__account_id__balance_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/interest-rates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Interest Rates
     * @description List an account's rates, newest first.
     */
    get: operations['list_interest_rates_api_v1_accounts__account_id__interest_rates_get']
    put?: never
    /**
     * Create Rate
     * @description Record a rate from a given date. Earlier rates are left untouched.
     */
    post: operations['create_rate_api_v1_accounts__account_id__interest_rates_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/interest-rates/{rate_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Rate
     * @description Soft-delete a rate. The row is kept, so the history stays auditable.
     */
    delete: operations['delete_rate_api_v1_accounts__account_id__interest_rates__rate_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description The user's transactions, newest first, filtered and paginated.
     *
     *     `from` and `to` are inclusive dates on the transaction. The filters combine.
     */
    get: operations['index_api_v1_transactions_get']
    put?: never
    /**
     * Create
     * @description Record an expense, an income or a transfer.
     */
    post: operations['create_api_v1_transactions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions/{transaction_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Show
     * @description One transaction, with its postings.
     */
    get: operations['show_api_v1_transactions__transaction_id__get']
    put?: never
    post?: never
    /**
     * Destroy
     * @description Soft-delete a transaction and its postings. The rows are kept.
     */
    delete: operations['destroy_api_v1_transactions__transaction_id__delete']
    options?: never
    head?: never
    /**
     * Patch
     * @description Change the date, merchant, note, or the amount of a single posting.
     */
    patch: operations['patch_api_v1_transactions__transaction_id__patch']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AccountCreate
     * @description Fields accepted when creating an account.
     */
    AccountCreate: {
      /** Name */
      name: string
      type: components['schemas']['AccountType']
      /** Purpose */
      purpose?: string | null
      capture_mode: components['schemas']['CaptureMode']
      /** Parent Id */
      parent_id?: number | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /**
       * Opening Date
       * Format: date
       */
      opening_date: string
      /** Statement Day */
      statement_day?: number | null
      /** Due Day */
      due_day?: number | null
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
    }
    /**
     * AccountResponse
     * @description An account as returned by the API. Money is integer paise.
     */
    AccountResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      type: components['schemas']['AccountType']
      /** Purpose */
      purpose: string | null
      capture_mode: components['schemas']['CaptureMode']
      /** Parent Id */
      parent_id: number | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /**
       * Opening Date
       * Format: date
       */
      opening_date: string
      /** Statement Day */
      statement_day: number | null
      /** Due Day */
      due_day: number | null
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * AccountType
     * @description What kind of account this is. A pot is a named sub-balance of a parent.
     * @enum {string}
     */
    AccountType:
      'savings' | 'current' | 'credit_card' | 'wallet' | 'cash' | 'fd' | 'rd' | 'loan' | 'pot'
    /**
     * AccountUpdate
     * @description Fields that may change; omitted fields are left alone. `type` is fixed.
     */
    AccountUpdate: {
      /** Name */
      name?: string | null
      /** Purpose */
      purpose?: string | null
      capture_mode?: components['schemas']['CaptureMode'] | null
      /** Parent Id */
      parent_id?: number | null
      /** Opening Balance Paise */
      opening_balance_paise?: number | null
      /** Opening Date */
      opening_date?: string | null
      /** Statement Day */
      statement_day?: number | null
      /** Due Day */
      due_day?: number | null
      /** Is Active */
      is_active?: boolean | null
    }
    /**
     * BalanceResponse
     * @description An account's balance, and the two figures it was worked out from.
     *
     *     The parts are reported as well as the answer, so a figure can always be
     *     explained rather than merely trusted. Money is integer paise throughout.
     */
    BalanceResponse: {
      /** Account Id */
      account_id: number
      /** As Of */
      as_of: string | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /** Postings Paise */
      postings_paise: number
      /** Balance Paise */
      balance_paise: number
    }
    /**
     * CaptureMode
     * @description How the transactions for an account are expected to arrive.
     * @enum {string}
     */
    CaptureMode: 'statement_import' | 'manual_only' | 'hybrid'
    /**
     * ExpenseCreate
     * @description Money leaving one account. The amount is positive; the kind sets the sign.
     */
    ExpenseCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'expense'
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Health check result. `database` reflects a live query, not a guess.
     */
    HealthResponse: {
      /** Status */
      status: string
      /** Database */
      database: string
    }
    /**
     * IncomeCreate
     * @description Money arriving in one account.
     */
    IncomeCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'income'
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
    }
    /**
     * InterestRateCreate
     * @description Fields accepted when recording a rate. A change is a new record, never an edit.
     */
    InterestRateCreate: {
      /** Rate */
      rate: number | string
      /**
       * From Date
       * Format: date
       */
      from_date: string
      frequency: components['schemas']['RateFrequency']
      /** Note */
      note?: string | null
    }
    /**
     * InterestRateResponse
     * @description A rate as returned by the API.
     *
     *     `rate` is per cent per annum and is serialised as a string, so the exact
     *     decimal reaches the client without ever passing through a float. More than
     *     four decimal places are rejected rather than rounded.
     */
    InterestRateResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /** Rate */
      rate: string
      /**
       * From Date
       * Format: date
       */
      from_date: string
      frequency: components['schemas']['RateFrequency']
      /** Note */
      note: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * LoginRequest
     * @description Credentials sent to POST /auth/login.
     */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /**
     * PostingKind
     * @description What one account's side of a transaction is.
     *
     *     Only expense and income count as spending or earning; a transfer, a card
     *     payment, a refund and an adjustment must never be counted as either.
     * @enum {string}
     */
    PostingKind:
      'expense' | 'income' | 'transfer' | 'adjustment' | 'interest' | 'fee' | 'investment'
    /**
     * PostingResponse
     * @description One account's side of a transaction, as returned by the API.
     */
    PostingResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
      kind: components['schemas']['PostingKind']
    }
    /**
     * RateFrequency
     * @description How often interest at a given rate is credited.
     * @enum {string}
     */
    RateFrequency: 'daily' | 'monthly' | 'quarterly' | 'yearly'
    /**
     * TransactionResponse
     * @description A transaction and the postings that carry its amounts.
     */
    TransactionResponse: {
      /** Id */
      id: number
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant: string | null
      /** Note */
      note: string | null
      source: components['schemas']['TransactionSource']
      /** Postings */
      postings: components['schemas']['PostingResponse'][]
    }
    /**
     * TransactionSource
     * @description How a transaction arrived, so an imported batch can be reversed whole.
     * @enum {string}
     */
    TransactionSource: 'manual' | 'import' | 'recurring' | 'ai_approved'
    /**
     * TransactionUpdate
     * @description What may change. The accounts and the kind never do.
     *
     *     An omitted field is left alone; an explicit null clears it. The amount may
     *     only be changed when the transaction has a single posting, because a transfer
     *     is two postings that must keep summing to zero.
     */
    TransactionUpdate: {
      /** Transaction Date */
      transaction_date?: string | null
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /** Amount Paise */
      amount_paise?: number | null
    }
    /**
     * TransferCreate
     * @description Money moving between two accounts, as two postings that sum to zero.
     */
    TransferCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'transfer'
      /** From Account Id */
      from_account_id: number
      /** To Account Id */
      to_account_id: number
      /** Amount Paise */
      amount_paise: number
    }
    /**
     * UserResponse
     * @description The signed-in user. Never includes the password hash.
     */
    UserResponse: {
      /** Id */
      id: number
      /** Email */
      email: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  read_health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  read_me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
    }
  }
  index_api_v1_accounts_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_v1_accounts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  show_api_v1_accounts__account_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  destroy_api_v1_accounts__account_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  patch_api_v1_accounts__account_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_balance_api_v1_accounts__account_id__balance_get: {
    parameters: {
      query?: {
        as_of?: string | null
      }
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BalanceResponse']
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_interest_rates_api_v1_accounts__account_id__interest_rates_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InterestRateResponse'][]
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_rate_api_v1_accounts__account_id__interest_rates_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InterestRateCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InterestRateResponse']
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A live rate already starts on that date */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_rate_api_v1_accounts__account_id__interest_rates__rate_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
        rate_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The account or the rate does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  index_api_v1_transactions_get: {
    parameters: {
      query?: {
        account_id?: number | null
        from?: string | null
        to?: string | null
        kind?: components['schemas']['PostingKind'] | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_v1_transactions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ExpenseCreate']
          | components['schemas']['IncomeCreate']
          | components['schemas']['TransferCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description An account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  show_api_v1_transactions__transaction_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  destroy_api_v1_transactions__transaction_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  patch_api_v1_transactions__transaction_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransactionUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
