/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Health
     * @description Report service and database status; the check really queries Postgres.
     */
    get: operations['read_health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Verify credentials, start a session and set the session cookie.
     */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description End the session and clear the cookie.
     */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Me
     * @description Return the signed-in user.
     */
    get: operations['read_me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description List the signed-in user's live accounts, oldest first.
     */
    get: operations['index_api_v1_accounts_get']
    put?: never
    /**
     * Create
     * @description Create an account for the signed-in user.
     */
    post: operations['create_api_v1_accounts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Show
     * @description Return one account, or 404 when it is unknown or soft-deleted.
     */
    get: operations['show_api_v1_accounts__account_id__get']
    put?: never
    post?: never
    /**
     * Destroy
     * @description Soft-delete an account. The row and its history are kept.
     */
    delete: operations['destroy_api_v1_accounts__account_id__delete']
    options?: never
    head?: never
    /**
     * Patch
     * @description Apply the provided fields to an account. `type` cannot change.
     */
    patch: operations['patch_api_v1_accounts__account_id__patch']
    trace?: never
  }
  '/api/v1/accounts/{account_id}/balance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Balance
     * @description The account's balance, and the two figures it was worked out from.
     */
    get: operations['read_balance_api_v1_accounts__account_id__balance_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/interest-rates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Interest Rates
     * @description List an account's rates, newest first.
     */
    get: operations['list_interest_rates_api_v1_accounts__account_id__interest_rates_get']
    put?: never
    /**
     * Create Rate
     * @description Record a rate from a given date. Earlier rates are left untouched.
     */
    post: operations['create_rate_api_v1_accounts__account_id__interest_rates_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/interest-rates/{rate_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Rate
     * @description Soft-delete a rate. The row is kept, so the history stays auditable.
     */
    delete: operations['delete_rate_api_v1_accounts__account_id__interest_rates__rate_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/balance-checks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index Balance Checks
     * @description The account's balance checks, most recent first.
     */
    get: operations['index_balance_checks_api_v1_accounts__account_id__balance_checks_get']
    put?: never
    /**
     * Create Balance Check
     * @description Compare the ledger with the bank, and write the difference off if asked.
     *
     *     The threshold is advice, not a rule: a large difference is flagged and the
     *     write-off still happens when the user has decided on it.
     */
    post: operations['create_balance_check_api_v1_accounts__account_id__balance_checks_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/balance-checks/{check_id}/adjust': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Adjust Balance Check
     * @description Write off the difference a check found earlier.
     *
     *     The figures are the ones recorded at the time, so the write-off cannot drift
     *     from what the user actually saw.
     */
    post: operations['adjust_balance_check_api_v1_accounts__account_id__balance_checks__check_id__adjust_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{account_id}/adjustment-share': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Read Adjustment Share
     * @description Write-offs as a share of the month's spending, for the month given.
     */
    get: operations['read_adjustment_share_api_v1_accounts__account_id__adjustment_share_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description The user's transactions, newest first, filtered and paginated.
     *
     *     `from` and `to` are inclusive dates on the transaction. The filters combine.
     */
    get: operations['index_api_v1_transactions_get']
    put?: never
    /**
     * Create
     * @description Record an expense, an income or a transfer.
     */
    post: operations['create_api_v1_transactions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions/suggestions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Suggestions
     * @description The names worth offering for fast entry, most used first.
     *
     *     Each one carries how it was recorded last, so one tap records it again. `on`
     *     is the day to count the window back from, and defaults to today; a client
     *     sends it only when it is showing a day of its own.
     */
    get: operations['suggestions_api_v1_transactions_suggestions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions/streak': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Streak
     * @description How many days in a row something has been recorded, and whether today is one.
     */
    get: operations['streak_api_v1_transactions_streak_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions/{transaction_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Show
     * @description One transaction, with its postings.
     */
    get: operations['show_api_v1_transactions__transaction_id__get']
    put?: never
    post?: never
    /**
     * Destroy
     * @description Soft-delete a transaction and its postings. The rows are kept.
     */
    delete: operations['destroy_api_v1_transactions__transaction_id__delete']
    options?: never
    head?: never
    /**
     * Patch
     * @description Change the date, merchant, note, the amount, or the filing of a movement.
     */
    patch: operations['patch_api_v1_transactions__transaction_id__patch']
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description The user's categories: each branch, then the names under it.
     */
    get: operations['index_api_v1_categories_get']
    put?: never
    /**
     * Create
     * @description Add a name to the tree, as a branch of its own or under one.
     */
    post: operations['create_api_v1_categories_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{category_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove
     * @description Remove a category. The row is kept, so the history stays readable.
     */
    delete: operations['remove_api_v1_categories__category_id__delete']
    options?: never
    head?: never
    /**
     * Update
     * @description Rename a category, move it in the tree, or both.
     */
    patch: operations['update_api_v1_categories__category_id__patch']
    trace?: never
  }
  '/api/v1/categories/spend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Spend
     * @description What was spent in a period: every expense category, and the money in none.
     *
     *     `from` and `to` are inclusive dates on the transaction, and either may be
     *     left out. A category with nothing spent is a row of zeros rather than a
     *     missing row, so the tree the client draws is the whole tree; spending filed
     *     under no category has no row at all, so it comes back beside them and is
     *     counted in the period's `total_paise`.
     */
    get: operations['spend_api_v1_categories_spend_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Defaults
     * @description Seed the default set, which does something only on an empty tree.
     */
    post: operations['create_defaults_api_v1_categories_defaults_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Index
     * @description Every live item, paused ones included.
     */
    get: operations['index_api_v1_recurring_items_get']
    put?: never
    /**
     * Create
     * @description Plan something that repeats.
     */
    post: operations['create_api_v1_recurring_items_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items/due': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Due
     * @description What is owed on a day: the active items, on their day, not yet settled.
     */
    get: operations['due_api_v1_recurring_items_due_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items/{item_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove
     * @description Remove an item. The periods it already dealt with keep their record.
     */
    delete: operations['remove_api_v1_recurring_items__item_id__delete']
    options?: never
    head?: never
    /**
     * Update
     * @description Change an item's plan, never the money it has already recorded.
     */
    patch: operations['update_api_v1_recurring_items__item_id__patch']
    trace?: never
  }
  '/api/v1/recurring-items/{item_id}/pause': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Pause
     * @description Stop offering this item. Nothing owed is recorded.
     */
    post: operations['pause_api_v1_recurring_items__item_id__pause_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items/{item_id}/resume': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Resume
     * @description Start offering this item again.
     */
    post: operations['resume_api_v1_recurring_items__item_id__resume_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items/{item_id}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm
     * @description Record this period's money, as one movement dated the day it was owed.
     */
    post: operations['confirm_api_v1_recurring_items__item_id__confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/recurring-items/{item_id}/skip': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Skip
     * @description Say this period is not happening. Nothing is recorded at all.
     */
    post: operations['skip_api_v1_recurring_items__item_id__skip_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AccountCreate
     * @description Fields accepted when creating an account.
     */
    AccountCreate: {
      /** Name */
      name: string
      type: components['schemas']['AccountType']
      /** Purpose */
      purpose?: string | null
      capture_mode: components['schemas']['CaptureMode']
      /** Parent Id */
      parent_id?: number | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /**
       * Opening Date
       * Format: date
       */
      opening_date: string
      /** Statement Day */
      statement_day?: number | null
      /** Due Day */
      due_day?: number | null
      /**
       * Is Active
       * @default true
       */
      is_active: boolean
    }
    /**
     * AccountResponse
     * @description An account as returned by the API. Money is integer paise.
     */
    AccountResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      type: components['schemas']['AccountType']
      /** Purpose */
      purpose: string | null
      capture_mode: components['schemas']['CaptureMode']
      /** Parent Id */
      parent_id: number | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /**
       * Opening Date
       * Format: date
       */
      opening_date: string
      /** Statement Day */
      statement_day: number | null
      /** Due Day */
      due_day: number | null
      /** Is Active */
      is_active: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * AccountType
     * @description What kind of account this is. A pot is a named sub-balance of a parent.
     * @enum {string}
     */
    AccountType:
      'savings' | 'current' | 'credit_card' | 'wallet' | 'cash' | 'fd' | 'rd' | 'loan' | 'pot'
    /**
     * AccountUpdate
     * @description Fields that may change; omitted fields are left alone. `type` is fixed.
     */
    AccountUpdate: {
      /** Name */
      name?: string | null
      /** Purpose */
      purpose?: string | null
      capture_mode?: components['schemas']['CaptureMode'] | null
      /** Parent Id */
      parent_id?: number | null
      /** Opening Balance Paise */
      opening_balance_paise?: number | null
      /** Opening Date */
      opening_date?: string | null
      /** Statement Day */
      statement_day?: number | null
      /** Due Day */
      due_day?: number | null
      /** Is Active */
      is_active?: boolean | null
    }
    /**
     * AdjustmentShareResponse
     * @description Write-offs against spending for one month, as positive magnitudes.
     */
    AdjustmentShareResponse: {
      /**
       * Month
       * Format: date
       */
      month: string
      /** Spend Paise */
      spend_paise: number
      /** Adjustments Paise */
      adjustments_paise: number
      /** Share Percent */
      share_percent: number
    }
    /**
     * BalanceCheckCreate
     * @description What the user brings: the real balance, and whether to write the gap off.
     *
     *     `adjust` has no default on purpose. Writing a difference off moves real
     *     figures, so the request has to say what it wants rather than have it assumed.
     */
    BalanceCheckCreate: {
      /**
       * On
       * Format: date
       */
      on: string
      /** Stated Balance Paise */
      stated_balance_paise: number
      /** Adjust */
      adjust: boolean
    }
    /**
     * BalanceCheckResponse
     * @description The answer to a check just made, including the nudge.
     *
     *     The warning is advice about what has just happened by today's threshold, so
     *     it belongs to this answer and not to the history of past checks.
     */
    BalanceCheckResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /**
       * Checked On
       * Format: date
       */
      checked_on: string
      /** Computed Balance Paise */
      computed_balance_paise: number
      /** Stated Balance Paise */
      stated_balance_paise: number
      /** Difference Paise */
      difference_paise: number
      /** Adjustment Transaction Id */
      adjustment_transaction_id: number | null
      /** Warning */
      warning: boolean
      /** Threshold Paise */
      threshold_paise: number
    }
    /**
     * BalanceCheckSummaryResponse
     * @description One check as it is kept: the figures, as they were at the time.
     */
    BalanceCheckSummaryResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /**
       * Checked On
       * Format: date
       */
      checked_on: string
      /** Computed Balance Paise */
      computed_balance_paise: number
      /** Stated Balance Paise */
      stated_balance_paise: number
      /** Difference Paise */
      difference_paise: number
      /** Adjustment Transaction Id */
      adjustment_transaction_id: number | null
    }
    /**
     * BalanceResponse
     * @description An account's balance, and the two figures it was worked out from.
     *
     *     The parts are reported as well as the answer, so a figure can always be
     *     explained rather than merely trusted. Money is integer paise throughout.
     */
    BalanceResponse: {
      /** Account Id */
      account_id: number
      /** As Of */
      as_of: string | null
      /** Opening Balance Paise */
      opening_balance_paise: number
      /** Postings Paise */
      postings_paise: number
      /** Balance Paise */
      balance_paise: number
    }
    /**
     * CaptureMode
     * @description How the transactions for an account are expected to arrive.
     * @enum {string}
     */
    CaptureMode: 'statement_import' | 'manual_only' | 'hybrid'
    /**
     * CategoryCreate
     * @description A new name in the tree.
     *
     *     `kind` is required for a top-level category and ignored for a child, which
     *     carries its parent's kind; the service words the refusal either way.
     */
    CategoryCreate: {
      /** Name */
      name: string
      kind?: components['schemas']['CategoryKind'] | null
      /** Parent Id */
      parent_id?: number | null
    }
    /**
     * CategoryKind
     * @description What a category is for, which its children inherit from it.
     *
     *     `adjustment` is the kind the two write-off names carry, so a balance check's
     *     difference has a home without pretending to be spending or income.
     * @enum {string}
     */
    CategoryKind: 'expense' | 'income' | 'adjustment'
    /**
     * CategoryResponse
     * @description One category as it is kept.
     */
    CategoryResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Parent Id */
      parent_id: number | null
      kind: components['schemas']['CategoryKind']
    }
    /**
     * CategorySpendResponse
     * @description One row of the spend report.
     *
     *     `direct_paise` is what was filed under this category itself; `total_paise`
     *     adds everything filed under its children, so a group answers for its whole
     *     branch. Categories with nothing spent are rows too, with zeros.
     */
    CategorySpendResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Parent Id */
      parent_id: number | null
      kind: components['schemas']['CategoryKind']
      /** Direct Paise */
      direct_paise: number
      /** Total Paise */
      total_paise: number
    }
    /**
     * CategoryUpdate
     * @description What may change: the name, where it sits, or both.
     *
     *     An omitted field is left alone; an explicit `parent_id: null` moves the
     *     category to the top level, which is why the router tells the difference.
     */
    CategoryUpdate: {
      /** Name */
      name?: string | null
      /** Parent Id */
      parent_id?: number | null
    }
    /**
     * ConfirmRequest
     * @description Confirming a period, optionally for a different amount this time.
     */
    ConfirmRequest: {
      /** Amount Paise */
      amount_paise?: number | null
    }
    /**
     * ConfirmedResponse
     * @description What confirming wrote: the item, the day, and the movement that recorded it.
     */
    ConfirmedResponse: {
      item: components['schemas']['RecurringItemResponse']
      /**
       * Due On
       * Format: date
       */
      due_on: string
      /** Transaction Id */
      transaction_id: number
    }
    /**
     * DefaultsResponse
     * @description What the default set added, which is nothing when the tree was not empty.
     */
    DefaultsResponse: {
      /** Created */
      created: components['schemas']['CategoryResponse'][]
    }
    /**
     * DueItemResponse
     * @description An item and the day it is owed for.
     *
     *     The day comes out with the item because it is not always today: a rent due on
     *     the 1st that is confirmed on the 28th is still the 1st's rent, and the row
     *     that gets written has to say so.
     */
    DueItemResponse: {
      item: components['schemas']['RecurringItemResponse']
      /**
       * Due On
       * Format: date
       */
      due_on: string
    }
    /**
     * ExpenseCreate
     * @description Money leaving one account. The amount is positive; the kind sets the sign.
     */
    ExpenseCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
      /** Category Id */
      category_id?: number | null
      /** Parts */
      parts?: components['schemas']['SplitPartCreate'][] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'expense'
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Health check result. `database` reflects a live query, not a guess.
     */
    HealthResponse: {
      /** Status */
      status: string
      /** Database */
      database: string
    }
    /**
     * IncomeCreate
     * @description Money arriving in one account.
     */
    IncomeCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
      /** Category Id */
      category_id?: number | null
      /** Parts */
      parts?: components['schemas']['SplitPartCreate'][] | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'income'
    }
    /**
     * InterestRateCreate
     * @description Fields accepted when recording a rate. A change is a new record, never an edit.
     */
    InterestRateCreate: {
      /** Rate */
      rate: number | string
      /**
       * From Date
       * Format: date
       */
      from_date: string
      frequency: components['schemas']['RateFrequency']
      /** Note */
      note?: string | null
    }
    /**
     * InterestRateResponse
     * @description A rate as returned by the API.
     *
     *     `rate` is per cent per annum and is serialised as a string, so the exact
     *     decimal reaches the client without ever passing through a float. More than
     *     four decimal places are rejected rather than rounded.
     */
    InterestRateResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /** Rate */
      rate: string
      /**
       * From Date
       * Format: date
       */
      from_date: string
      frequency: components['schemas']['RateFrequency']
      /** Note */
      note: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * LoginRequest
     * @description Credentials sent to POST /auth/login.
     */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /**
     * PostingKind
     * @description What one account's side of a transaction is.
     *
     *     Only expense and income count as spending or earning; a transfer, a card
     *     payment, a refund and an adjustment must never be counted as either.
     * @enum {string}
     */
    PostingKind:
      'expense' | 'income' | 'transfer' | 'adjustment' | 'interest' | 'fee' | 'investment'
    /**
     * PostingResponse
     * @description One account's side of a transaction, as returned by the API.
     */
    PostingResponse: {
      /** Id */
      id: number
      /** Account Id */
      account_id: number
      /** Amount Paise */
      amount_paise: number
      kind: components['schemas']['PostingKind']
      /** Category Id */
      category_id: number | null
    }
    /**
     * RateFrequency
     * @description How often interest at a given rate is credited.
     * @enum {string}
     */
    RateFrequency: 'daily' | 'monthly' | 'quarterly' | 'yearly'
    /**
     * RecurringFrequency
     * @description How often a recurring item comes round.
     *
     *     A monthly item names a day of the month; a weekly one names a weekday. The
     *     values match `app.core.recurrence.Frequency` word for word, so the calendar
     *     code reads a stored row without a translation table in between.
     * @enum {string}
     */
    RecurringFrequency: 'monthly' | 'weekly'
    /**
     * RecurringItemCreate
     * @description A new repeating item.
     *
     *     The rhythm is given whole with its frequency: a monthly item carries a day of
     *     the month, a weekly one a weekday, and the service refuses one that is half
     *     given rather than guessing which half was meant.
     */
    RecurringItemCreate: {
      /** Name */
      name: string
      kind: components['schemas']['PostingKind']
      /** Amount Paise */
      amount_paise: number
      /** Account Id */
      account_id: number
      frequency: components['schemas']['RecurringFrequency']
      /**
       * Starts On
       * Format: date
       */
      starts_on: string
      /** Day Of Month */
      day_of_month?: number | null
      /** Weekday */
      weekday?: number | null
      /** Category Id */
      category_id?: number | null
      /** Ends On */
      ends_on?: string | null
    }
    /**
     * RecurringItemResponse
     * @description One item as it is kept.
     */
    RecurringItemResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      kind: components['schemas']['PostingKind']
      /** Amount Paise */
      amount_paise: number
      /** Account Id */
      account_id: number
      /** Category Id */
      category_id: number | null
      frequency: components['schemas']['RecurringFrequency']
      /** Day Of Month */
      day_of_month: number | null
      /** Weekday */
      weekday: number | null
      /**
       * Starts On
       * Format: date
       */
      starts_on: string
      /** Ends On */
      ends_on: string | null
      /** Is Active */
      is_active: boolean
    }
    /**
     * RecurringItemUpdate
     * @description What may change. An omitted field is left alone.
     *
     *     `category_id: null` clears the filing, so the router asks whether the field
     *     was sent rather than reading its value. `frequency` changes the rhythm and
     *     brings its own day with it.
     */
    RecurringItemUpdate: {
      /** Name */
      name?: string | null
      /** Amount Paise */
      amount_paise?: number | null
      /** Account Id */
      account_id?: number | null
      /** Category Id */
      category_id?: number | null
      frequency?: components['schemas']['RecurringFrequency'] | null
      /** Day Of Month */
      day_of_month?: number | null
      /** Weekday */
      weekday?: number | null
      /** Starts On */
      starts_on?: string | null
      /** Ends On */
      ends_on?: string | null
    }
    /**
     * SpendReportResponse
     * @description A period's spending: the tree, the money in no category, and the whole.
     *
     *     Spending filed under no category has no row to appear in, so it is reported
     *     beside the rows rather than left out: otherwise the rows would not add up to
     *     what the period actually cost. `total_paise` is the two together, so a client
     *     never has to decide what counts as spending.
     */
    SpendReportResponse: {
      /** Rows */
      rows: components['schemas']['CategorySpendResponse'][]
      /** Uncategorised Paise */
      uncategorised_paise: number
      /** Total Paise */
      total_paise: number
    }
    /**
     * SplitPartCreate
     * @description One part of a movement the user split between categories.
     */
    SplitPartCreate: {
      /** Amount Paise */
      amount_paise: number
      /** Category Id */
      category_id: number
    }
    /**
     * StreakResponse
     * @description How many days in a row something has been recorded, and whether today is one.
     *
     *     A run that ended yesterday is not over: the day is not finished yet.
     */
    StreakResponse: {
      /** Days */
      days: number
      /** Today Recorded */
      today_recorded: boolean
    }
    /**
     * SuggestionResponse
     * @description One name to offer for fast entry, and how it was recorded last.
     *
     *     `times_used` is how often the name has been recorded, and the rest is the
     *     most recent time: one tap records the same thing again. `category_id` is null
     *     for a movement that was split, because a split has no single category.
     */
    SuggestionResponse: {
      /** Merchant */
      merchant: string
      /** Times Used */
      times_used: number
      /**
       * Last Used
       * Format: date
       */
      last_used: string
      /** Account Id */
      account_id: number
      /** Category Id */
      category_id: number | null
      /** Amount Paise */
      amount_paise: number
    }
    /**
     * TransactionResponse
     * @description A transaction and the postings that carry its amounts.
     */
    TransactionResponse: {
      /** Id */
      id: number
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant: string | null
      /** Note */
      note: string | null
      source: components['schemas']['TransactionSource']
      /** Postings */
      postings: components['schemas']['PostingResponse'][]
    }
    /**
     * TransactionSource
     * @description How a transaction arrived, so an imported batch can be reversed whole.
     * @enum {string}
     */
    TransactionSource: 'manual' | 'import' | 'recurring' | 'ai_approved'
    /**
     * TransactionUpdate
     * @description What may change. The accounts and the kind never do.
     *
     *     An omitted field is left alone; an explicit null clears it. The amount and
     *     the category may only be changed when the transaction has a single posting,
     *     because a transfer is two postings that must keep summing to zero.
     */
    TransactionUpdate: {
      /** Transaction Date */
      transaction_date?: string | null
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /** Amount Paise */
      amount_paise?: number | null
      /** Category Id */
      category_id?: number | null
    }
    /**
     * TransferCreate
     * @description Money moving between two accounts, as two postings that sum to zero.
     */
    TransferCreate: {
      /**
       * Transaction Date
       * Format: date
       */
      transaction_date: string
      /** Merchant */
      merchant?: string | null
      /** Note */
      note?: string | null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'transfer'
      /** From Account Id */
      from_account_id: number
      /** To Account Id */
      to_account_id: number
      /** Amount Paise */
      amount_paise: number
    }
    /**
     * UserResponse
     * @description The signed-in user. Never includes the password hash.
     */
    UserResponse: {
      /** Id */
      id: number
      /** Email */
      email: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  read_health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  read_me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
    }
  }
  index_api_v1_accounts_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_v1_accounts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  show_api_v1_accounts__account_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  destroy_api_v1_accounts__account_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  patch_api_v1_accounts__account_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_balance_api_v1_accounts__account_id__balance_get: {
    parameters: {
      query?: {
        as_of?: string | null
      }
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BalanceResponse']
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_interest_rates_api_v1_accounts__account_id__interest_rates_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InterestRateResponse'][]
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_rate_api_v1_accounts__account_id__interest_rates_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InterestRateCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InterestRateResponse']
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description A live rate already starts on that date */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_rate_api_v1_accounts__account_id__interest_rates__rate_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
        rate_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The account or the rate does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  index_balance_checks_api_v1_accounts__account_id__balance_checks_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BalanceCheckSummaryResponse'][]
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_balance_check_api_v1_accounts__account_id__balance_checks_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BalanceCheckCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BalanceCheckResponse']
        }
      }
      /** @description The check date is before the account opened */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  adjust_balance_check_api_v1_accounts__account_id__balance_checks__check_id__adjust_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: number
        check_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BalanceCheckResponse']
        }
      }
      /** @description The account or the check does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The check is already written off, or has no difference */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_adjustment_share_api_v1_accounts__account_id__adjustment_share_get: {
    parameters: {
      query?: {
        month?: string | null
      }
      header?: never
      path: {
        account_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentShareResponse']
        }
      }
      /** @description The account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  index_api_v1_transactions_get: {
    parameters: {
      query?: {
        account_id?: number | null
        from?: string | null
        to?: string | null
        kind?: components['schemas']['PostingKind'] | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_v1_transactions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ExpenseCreate']
          | components['schemas']['IncomeCreate']
          | components['schemas']['TransferCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description An account does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  suggestions_api_v1_transactions_suggestions_get: {
    parameters: {
      query?: {
        limit?: number
        on?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SuggestionResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  streak_api_v1_transactions_streak_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StreakResponse']
        }
      }
    }
  }
  show_api_v1_transactions__transaction_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  destroy_api_v1_transactions__transaction_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  patch_api_v1_transactions__transaction_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        transaction_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransactionUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TransactionResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The transaction does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  index_api_v1_categories_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryResponse'][]
        }
      }
    }
  }
  create_api_v1_categories_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryResponse']
        }
      }
      /** @description A rule of the tree was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_api_v1_categories__category_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        category_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The category does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Something is filed under the category */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_api_v1_categories__category_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        category_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryResponse']
        }
      }
      /** @description A rule of the tree was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The category does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  spend_api_v1_categories_spend_get: {
    parameters: {
      query?: {
        from?: string | null
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SpendReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_defaults_api_v1_categories_defaults_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DefaultsResponse']
        }
      }
    }
  }
  index_api_v1_recurring_items_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecurringItemResponse'][]
        }
      }
    }
  }
  create_api_v1_recurring_items_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecurringItemCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecurringItemResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description An account or category does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  due_api_v1_recurring_items_due_get: {
    parameters: {
      query?: {
        /** @description The day to ask about; today if omitted */
        on?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DueItemResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_api_v1_recurring_items__item_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_api_v1_recurring_items__item_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecurringItemUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecurringItemResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  pause_api_v1_recurring_items__item_id__pause_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecurringItemResponse']
        }
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  resume_api_v1_recurring_items__item_id__resume_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecurringItemResponse']
        }
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_api_v1_recurring_items__item_id__confirm_post: {
    parameters: {
      query?: {
        /** @description The day to ask about; today if omitted */
        on?: string | null
      }
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['ConfirmRequest'] | null
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfirmedResponse']
        }
      }
      /** @description A rule the database holds was broken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The period is already settled */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  skip_api_v1_recurring_items__item_id__skip_post: {
    parameters: {
      query?: {
        /** @description The day to ask about; today if omitted */
        on?: string | null
      }
      header?: never
      path: {
        item_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DueItemResponse']
        }
      }
      /** @description The item does not exist */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The period is already settled */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
